import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/context/AuthContext";

import { CartProvider } from "@/context/CartContext";
import { ThemeProvider } from "@/context/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ShopSpHere - Your Online Store",
  description: "Generated by create next app",
  icons:{
    icon: "/favicon.webp"
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col">
        <ThemeProvider>
          <AuthProvider>
        <CartProvider>
          <Suspense fallback={null}>
            <Navbar/>
          </Suspense>
        
          <main className="">{children}</main> 
        <Footer/>
        </CartProvider>
        </AuthProvider>
        </ThemeProvider>
        </body>
    </html>
  );
}
